### PR TITLE
Output file option

### PR DESCRIPTION
**Pull request by willsteinmetz**
This pull request adds the option to output the results of the hinting with the options to the console, text files, JSON file, and/or checkstyle format.

### CODE REVIEW

**Comment by poppinlp** [comment]
@willsteinmetz 
Hi.
Looks like travis build failed. Could you please fix it?  
You could remove nodejs 0.10 and 0.12 in travis. We may just support stable and LTS nodejs version for using new feature in dev.

**Comment by willsteinmetz** [comment]
I don't think I have access to update things in Travis. However, I can update the package.json file. I can update it to either 0.12 since that is passing or 4.0.0 since I believe that is the current LTS stable line.

**Comment by willsteinmetz** [comment]
Nevermind, found the setting. Pushing in a moment.

**Comment by poppinlp** [comment]
Great. THX.

**Pull request merged**
