### PR TITLE
update dependencies, fix npm vulnerabilities

### PR DESCRIPTION
**Pull request by FelixFurtmayr**

### CODE REVIEW

**Comment by poppinlp** [comment]
Thank you so much. I'll take a look at it tonight. :)

**Comment by FelixFurtmayr** [comment]
Thank YOU so much for the package :-)
Removes all my html errors ;-)
Just tell me if something should not work correct; I will fix it.

**Comment by FelixFurtmayr** [comment]
Hi poppinlp, could you also publish the new version on npm? 
I'm glad that I could add something to your work.

**Comment by poppinlp** [comment]
Yes, of course. I'll publish a new version today. :)

**Comment by poppinlp** [comment]
@FelixFurtmayr  Sorry. I got a really busy day.
I've published 0.6.0 which contains this PR just now.
And recently I'll publish a 1.0.0 version which will move to grunt 1.x.x and update the nodeJS versions for tests.

**Comment by FelixFurtmayr** [comment]
Great! Thank you.

**Pull request merged**
